flights_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: flights_db
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "dbt_{{ env_var('USER', 'default') }}"
      threads: 4
