name: "flights_data_models"
version: "2.0.0"
config-version: 2

profile: "flights_project"

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  flights_data_models:
    staging:
      +schema: dbt_bronze
      +materialized: view
      +tags: ["bronze", "raw", "staging"]

    intermediate:
      +schema: dbt_silver
      +materialized: table
      +tags: ["silver", "clean"]

    marts:
      +schema: dbt_gold
      +materialized: table
      +tags: ["gold", "mart"]
