name: "flights_datawarehouse"
version: "2.0.0"
config-version: 2

profile: "flights_project"

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  flights_datawarehouse:
    raw:
      +schema: dbt_raw
      +materialized: view
      +tags: ["bronze", "raw", "staging"]

    silver:
      +schema: dbt_silver
      +materialized: table
      +tags: ["clean", "silver"]

    gold:
      +schema: dbt_gold
      +materialized: table
      +tags: ["gold", "mart"]
